### ISSUE TITLE
Laravel 5.5 Interface 'Illuminate\View\Engines\EngineInterface' not found

### ISSUE THREAD

**Issue by hugeps** [krowinski/laravel-xslt#1]
Think the problem is around here:

-use Illuminate\View\Engines\EngineInterface;
+use Illuminate\Contracts\View\Engine as EngineInterface;

**Comment by krowinski** [comment]
Yes it was changed in laravel 5.5  I will fix this and create new tag

**Comment by krowinski** [comment]
fixed in tag 3.0.0

**Comment by hugeps** [comment]
Star
